// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvstrnyrpxxdvisbeupj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2c3RybnlycHh4ZHZpc2JldXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzk1OTIsImV4cCI6MjA3MDg1NTU5Mn0.6Fqtyd5gA62mLh6jSrS3eHew3y08Ib1t872STh-fPlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});